<?php

namespace Database\Seeders;

use App\Models\ProductIngredient;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductIngredientSeeder extends Seeder
{
    public function run(): void
    {
        $productIngredients = [
            '7 grain flakes',
            '8 grain flakes',
            "Adzuki beans' germs",
            'Agar',
            'Agave syrup',
            'Alfalfa sprouts',
            'Almond butter',
            'Almond flour',
            'Almond mass',
            'Almond milk/ almond drink',
            'Almond oil',
            'Almonds',
            'Amaranth seeds',
            'Apple',
            'Apple canned',
            'Apple jam',
            'Apple juice',
            'Apple puree',
            'Apple vinegar',
            'Apple, dried',
            'Apricot',
            'Apricot jam',
            'Apricot nectar',
            'Apricot, dried',
            'Apricots, canned',
            'Aroma salt',
            'Artichoke',
            'Asparagus',
            'Asparagus cabbage',
            'Asparagus, canned',
            'Aspartame, powder (E951)',
            'Atlantic herring',
            'Aubergine / Eggplant / Brinjal',
            'Avocado / Butter pear / Alligator pear',
            'Avocado oil',
            'Ayran',
            'Baking powder',
            'Baking soda',
            'Balsamic vinegar',
            'Baltic herring',
            'Bamboo shoots',
            'Bamboo shoots, canned',
            'Banana',
            'Banana, dried',
            'Barbeque sauce',
            'Barley',
            'Barley bread flour',
            'Barley flour',
            'Barley malt',
            'Barley rolled grains',
            'Basil',
            'Basil, fresh',
            'Beans',
            'Beans, canned',
            'Beans, dried',
            'Beef',
            'Beef brisket',
            'Beef chuck',
            'Beef heart',
            'Beef hock',
            'Beef kidney',
            'Beef liver',
            'Beef minced meat',
            'Beef roast',
            'Beef shoulder',
            'Beef striploin',
            'Beef T-bone steak / Porterhouse steak',
            'Beef tenderloin',
            'Beef tongue',
            'Beer',
            'Beet / Beetroot',
            'Beet juice',
            'Beet, canned',
            'Berries',
            'Black bread',
            'Black olives, canned',
            'Black pepper',
            'Black Pudding / Blood Pudding / Blood Sausage',
            'Blackberries',
            'Blackberries, frozen',
            'Blackberry jam',
            'Blackcurrant canned',
            'Blackcurrant jam',
            'Blackcurrants',
            'Blood powder',
            'Blue cheese',
            'Blueberries',
            'Blueberries, dried',
            'Blueberries, frozen',
            'Blueberry jam',
            'Bok choy',
            'Boston gherkins, canned',
            'Bouillon powder',
            'Bouillon powder, chicken',
            'Bouillon powder, fish',
            'Bouillon powder, lobster',
            'Bouillon powder, meat',
            'Bouillon powder, vegetable',
            'Bouillon, chicken',
            'Bouillon, fish',
            'Bouillon, meat',
            'Bouillon, vegetable',
            'Brazil nuts',
            'Bread cheese',
            'Bread improver mix',
            'Breadcrumbs',
            'Bream',
            'Brie white cheese',
            'Broccoli',
            'Broccoli, frozen',
            'Broiler',
            'Broiler gizzard',
            'Broiler heart',
            'Broiler leg',
            'Broiler liver',
            'Broiler neck',
            'Brown sugar',
            'Brussels sprouts',
            'Buckwheat flour',
            'Buckwheat pasta',
            'Bulgur',
            'Burbot',
            'Burgundy snail',
            'Butter',
            'Buttermilk',
            'Cabbage, red',
            'Cabbage, white',
            'Calendula',
            'Calluna vulgaris',
            'Calogen Neutral',
            'Camembert cheese',
            'Cantaloupe',
            'Capers, canned',
            'Carambola / Star fruit',
            'Caraway seeds / Meridian Fennel / Persian cumin',
            'Cardamom',
            'Carob flour / Carob powder',
            'Carp',
            'Carrageenan (E 407)',
            'Carrot',
            'Carrot juice',
            'Carrot marmelade',
            'Carrots, canned',
            'Cashew nuts',
            'Cassava',
            'Catfish',
            'Cauliflower',
            'Caviar, black / red',
            'Cayenne pepper',
            'Celeriac',
            'Celery',
            'Celery, fresh',
            'Centaurea cyanus',
            'Cereal bar',
            'Champagne',
            'Champignons',
            'Champignons, canned',
            'Chantarelles',
            'Cheese',
            'Cheese spread',
            'Cherimoya / Custard apple',
            'Cherry canned',
            'Cherry jam',
            'Cherry nectar',
            'Chestnut flour',
            'Chestnuts',
            'Chia seeds',
            'Chicken',
            'Chicken breast fillet',
            'Chicken drumsticks',
            'Chicken fat',
            'Chicken leg',
            'Chicken minced meat',
            'Chicken skin',
            'Chicken thigh',
            "Chicken wings",
            "Chickpeas",
            "Chicory coffee",
            "Chilli pepper",
            "Chilli pepper, fresh",
            "Chilli sauce, sweet",
            "Chinese cabbage / Napa cabbage / Celery cabbage / Peking cabbage",
            "Chives",
            "Chocolate",
            "Chokeberries",
            "Ciabatta",
            "Cinnamon / Cassia",
            "Cloudberries",
            "Cloudberry jam",
            "Clove",
            "Coarse salt",
            "Cocoa butter",
            "Coconut",
            "Coconut fat / Coconut butter",
            "Coconut flakes",
            "Coconut milk, canned",
            "Coconut oil",
            "Cod",
            "Coffee cream",
            "Coffee powder, soluble",
            "Cognac / Brandy",
            "Condensed milk",
            "Coriander seeds",
            "Coriander, fresh",
            "Corn / Glycose syrup, dark",
            "Corn / Maize",
            "Corn / Maize, frozen",
            "Corn flakes",
            "Corn oil",
            "Corn pasta",
            "Corn, canned",
            "Cornmeal / Corn meal / Polenta",
            "Cornstarch / Cornflour / Maize starch",
            "Cottage cheese",
            "Couscous",
            "Crab, canned",
            "Cranberries",
            "Cranberries, dried",
            "Cranberry jam",
            "Cranberry juice",
            "Crayfish",
            "Cream cheese",
            "Cream for cooking",
            "Cream of balsamic vinegar",
            "Creme Fraiche cream",
            "Cress",
            "Crisp bread",
            "Crushed tomatoes, canned",
            "Cucumber",
            "Cumin",
            "Curd cheese",
            "Curry paste",
            "Curry powder",
            "Cuttlefish",
            "Damson plum",
            "Dandelion leaves",
            "Dates",
            "Dates, dried",
            "Demerara sugar",
            "Dextrose",
            "Dill, fresh",
            "Dry yeast",
            "Duck",
            "Duck egg",
            "Durum wheat flour / Durum semolina",
            "Edam cheese",
            "Edamame beans",
            "Eel / Anguille",
            "Egg",
            "Egg noodles",
            "Egg white / albumen",
            "Egg yolk",
            "Elderberries",
            "Emmental cheese",
            "Endiivia salad, broad-leaved",
            "Endive",
            "European whitefish",
            "Farin sugar",
            "Fennel",
            "Fenugreek seeds",
            "Feta cheese",
            "Field beans / Broad beans / Fava beans",
            "Figs",
            "Figs, dried",
            "Filo / Fillo / Phyllo dough",
            "Fish",
            "Fish sauce",
            "Fish, dried",
            "Flax flour",
            "Flounder",
            "Flour mix",
            "Flowering quince",
            "Food thickener",
            "French fries / chips, frozen",
            "French mustard",
            "Fried Chillies",
            "Frog legs",
            "Frozen carrot, peas, cauliflower, beans",
            "Frozen peas, carrots",
            "Frozen peas, sweet corn, sweet pepper",
            "Frozen vegetables",
            "Fructose, powder",
            "Garam masala",
            "Garlic",
            "Garlic, canned",
            "Gelatin",
            "Ghee butter",
            "Gherkin, canned",
            "Gin",
            "Ginger",
            "Ginger root, fresh",
            "Glass noodles",
            "Glucose-fructose syrup",
            "Glycerol (E422)",
            "Glycose, powder",
            "Goat cheese",
            "Goat milk",
            "Goji berries",
            "Goose",
            "Goose egg",
            'Goose fat',
            'Gooseberries',
            'Gooseberry jam',
            'Gooseberry, canned',
            'Gouda cheese',
            'Goutweed / Aegopodium, Bishopsweed',
            'Granola bar',
            'Grape juice',
            'Grape nectar',
            'Grapefruit',
            'Grapefruit juice',
            'Grapes',
            'Grapeseed oil',
            'Greek yoghurt',
            'Green beans / Snap beans / Wax beans / String beans / French beans',
            'Green olives, canned',
            'Green onion',
            'Ground coffee / Coffee powder',
            'Groundcherry',
            'Guar gum / Guaran (E412)',
            'Guava',
            'Hake',
            'Halvah / Halva / Halavah',
            'Hamburger bun',
            'Hazelnuts',
            'Head lettuce',
            'Hemp flour',
            'Hemp seed',
            'Hemp seed oil',
            'Herb salt',
            'Herring',
            'Herring roe',
            'Honey',
            'Honey comb',
            'Honeydew melon, yellow melon',
            'Horse meat',
            'Horseradish, canned',
            'Horseradish, fresh',
            'Hot and sweet sauce',
            'Hot chocolate powder',
            'Ice tea',
            'Iceberg lettuce',
            'Inulin',
            'Jam',
            'Jelly powder',
            'Jerusalem artichoke / Sunchoke / Topinambur / Sunroot / Earth apple',
            'Juice',
            'Kale / Borecole',
            'Kama flour',
            'Kefir / Kephir',
            'Ketchup',
            'Kidney',
            'Kiwifruit / Chinese gooseberry',
            'Kiwifruit, canned',
            'Kohlrabi / Cabbage turnip / German turnip',
            'Lamb meat',
            'Lapimaa cheese',
            'Lavaret',
            'Lavash / Armenian bread',
            'Leaf beet / Swiss chard / Mangold / Spinach beet',
            'Leaf lettuce',
            'Lecithin (E322)',
            'Leek',
            'Lemon',
            'Lemon juice',
            'Lemon pepper',
            'Lemon zest / Lemon peel',
            'Lentil sprouts / Sprouted lentils',
            'Lentils / Daals / Dals',
            'Lime',
            'Lime juice',
            'Lime zest / Lime peel',
            'Lingonberries',
            'Lingonberry jam',
            'Linseed / Flaxseed',
            'Linseed / flaxseed oil',
            'Liquor',
            'Litchi / Lychee, dried',
            'Lollo rosso',
            'Lupini beans',
            'Lychee / Litchi / Leetchee',
            'Macadamia nut',
            'Mackerel',
            'Malt extract',
            'Malt syrup',
            'Maltodextrin',
            'Mandarin orange / Mandarine / Clementine / Tangerine',
            'Mandarines, canned',
            'Mango',
            'Mangosteen',
            'Mangosteen, canned',
            'Maple syrup',
            'Margarine',
            'Marjoram',
            'Marmelade spread',
            'Marzipan',
            'Mayonnaise',
            'Melon',
            'Melon seeds',
            'Meringue',
            'Milk',
            'Milk chocolate',
            'Milk powder',
            'Milk, lactose-free',
            'Millet flour',
            'Millet groats',
            'Minced meat, pork-beef',
            'Mineral water',
            'Miso paste',
            'Mixed cereal rolled grains',
            'Mixed flour',
            'Mixed fruit, canned',
            'Mixed fruit, dried',
            'Mixed mushrooms',
            'Mixed mushrooms, canned',
            'Molasses',
            'Moose meat',
            'Mozzarella cheese',
            'Mullet',
            'Multigrain flour mix',
            'Mung bean sprouts',
            'Mung beans',
            'Muscovado sugar',
            'Mussels, canned',
            'Mustard',
            'Mustard seeds',
            'Mutton meat',
            'Nectarine',
            'Nori seaweed sheets, dried',
            'Nut butter',
            'Nutmeg',
            'Nutritional yeast',
            'Nuts',
            'Oat bran',
            'Oat drink',
            'Oat fibers',
            'Oat flour, whole grain',
            'Oat milk / Oat drink',
            'Oat rolled grains / Oatmeal',
            'Octopus',
            'Oil',
            'Olive oil, cold-pressed',
            'Onion',
            'Orange',
            'Orange juice',
            'Orange marmelade',
            'Orange pepper',
            'Orange zest / Orange peel',
            'Oregano',
            'Oregano, fresh',
            'Oyster sauce',
            'Oysters, canned',
            'Palm oil',
            'Pan-salt',
            'Pangasius / Pangas / Panga / Bassa / Basa',
            'Papaya / Pawpaw',
            'Papaya nectar',
            'Papaya, dried',
            'Paprika spice',
            'Paradise apple',
            'Parmesan cheese',
            'Parsley',
            'Parsley root',
            'Parsley, fresh',
            'Parsnip',
            'Passion fruit',
            'Pasta',
            'Pastila',
            'Peach',
            'Peach nectar',
            'Peach, canned',
            'Peach, dried',
            'Peanut butter',
            'Peanut oil',
            'Peanut',
            'Pear',
            'Pear juice',
            'Pear, canned',
            'Pear, dried',
            'Pearl onions, canned',
            'Peas',
            'Peas, canned',
            'Peas, frozen',
            'Pecan nut',
            'Pectin (E440)',
            'Peppermint, fresh',
            'Perch',
            'Persimmon / Kaki fruit / Sharon fruit / Date-plum',
            'Pesto sauce',
            'Pheasant',
            'Pickled gherkin',
            'Pike',
            'Pike-pearch / Pikepearch / Zander, fresh',
            'Pine nuts',
            'Pineapple',
            'Pineapple juice',
            'Pineapple, canned',
            'Pineapple, dried',
            'Pistachio nuts',
            'Pistachio pasta',
            'Pitaya, Dragonfruit',
            'Plum',
            'Plum canned',
            'Plum jam',
            'Plum nectar',
            'Plums, canned',
            'Pomegranate',
            'Pomegranate juice',
            'Pomelo / Pummelo / Pommelo',
            'Poppy mix',
            'Poppy seeds',
            'Pork',
            'Pork bacon',
            'Pork blood',
            'Pork fat',
            'Pork feet or trotters',
            'Pork ham',
            'Pork kidney',
            'Pork lard',
            'Pork liver',
            'Pork meat, collar / chops',
            'Pork minced meat',
            'Pork ribs',
            'Pork shoulder',
            'Pork striploin',
            'Pork tenderloin',
            'Port',
            'Potato',
            'Potato flakes',
            'Potato puree powder',
            'Potato seasoning mix',
            'Potato starch',
            'Prune / Plum, dried',
            'Psyllium husk',
            'Puff pastry, frozen',
            'Pumpkin',
            'Pumpkin seed oil',
            'Pumpkin seeds',
            'Pumpkin, canned',
            'Quail egg',
            'Quark',
            'Quark cream',
            'Quinoa',
            'Rabbit meat',
            'Radicchio (Italian chicory)',
            'Radish',
            'Rainbow trout',
            'Raisins',
            'Rambotan, canned',
            'Ramsons',
            'Rape seed oil',
            'Raspberries',
            'Raspberries, frozen',
            'Raspberry canned',
            'Raspberry jam',
            'Red malt',
            'Red rice',
            'Redcurrant jam',
            'Redcurrants',
            'Reindeer meat',
            'Rhubarb',
            'Rhubarb jam',
            'Rice',
            'Rice drink',
            'Rice flakes',
            'Rice flour',
            'Rice milk / Rice drink',
            'Rice noodles',
            'Rice paper',
            'Rice starch',
            'Rice vinegar',
            'Ricotta quark',
            'Rocket salad / Arugula',
            'Romaine / cos lettuce',
            'Root beer',
            'Rose hip jam',
            'Rose hips / Rosehips',
            'Rose hips / Rosehips, dried',
            'Rosemary',
            'Rosemary, fresh',
            'Rowanberries',
            'Rum',
            'Rusk',
            'Rye bread',
            'Rye flakes',
            'Rye flour',
            'Rye flour, whole grain',
            'Rye grains',
            'Rye malt',
            'Saccharine (E954)',
            'Saffron',
            'Sage, fresh',
            'Saida',
            'Saithe',
            'Salmon',
            'Salt',
            'Salty nuts',
            'Sauerkraut / Sour cabbage',
            'Savoy cabbage',
            'Scallop',
            "Scorzonera / Black salsify / Spanish salsify / Vegetable oyster",
            "Sea buckthorn berries",
            "Sea salt",
            "Sea trout / Brown trout",
            "Semolina",
            "Sesame seed oil",
            "Sesame seeds",
            "Sheatfish",
            "Sheep milk",
            "Shrimps / Prawns, canned",
            "Shrimps / Prawns, frozen",
            "Skyr",
            "Smoked cheese",
            "Snails, canned",
            "Snowcock",
            "Soft tortilla",
            "Soija90 - soya protein isolate",
            "Sorbitol (E420)",
            "Sorrel / Dock / Sour grass",
            "Sour cherry / Sweet cherry",
            "Soured / cultured milk",
            "Soy flakes",
            "Soy milk / Soy drink",
            "Soy protein",
            "Soy sauce",
            "Soya beans",
            "Soya oil",
            "Soya sauce",
            "Spelt flour, wholemeal",
            "Spelt, whole grain",
            "Spinach",
            "Spinach, frozen",
            "Spirulina seaweed, dried",
            "Squash / Zucchini / Marrow",
            "Squid",
            "Stawberry jam",
            "Stinging nettle",
            "Strawberries",
            "Strawberry canned",
            "Sturgeon",
            "Succade",
            "Sucralose, powder (E955)",
            "Sugar",
            "Sugar syrup",
            "Sugar-snap peas / Snow peas / Mangetouts",
            "Sunflower oil",
            "Sunflower seeds",
            "Sushi vinegar",
            "Swede / Rutabaga / Swedish turnip / Yellow turnip",
            "Sweet pepper / Bell pepper / Capsicum",
            "Sweet pepper, canned",
            "Sweet potato",
            "Tahini",
            "Tamari sauce",
            "Tamarind, pulp",
            "Tapioca",
            "Teriyaki sauce",
            "Thai sauce",
            "Thyme",
            "Thyme, fresh",
            "Tilapia",
            "Tofu",
            "Tomato",
            "Tomato juice",
            "Tomato paste",
            "Tomato puree",
            "Tomatoes, canned",
            "Tomatoes, sun-dried, canned",
            "Triticale flour",
            "Tuna fish",
            "Turkey",
            "Turkey breast fillet",
            "Turkey skin",
            "Turkey thigh",
            "Turmeric / Indian Saffron",
            "Turnip",
            "Vanilla sugar",
            "Veal",
            "Veal breast",
            "Veal chops",
            "Veal liver",
            "Veal roast",
            "Veal shoulder",
            "Vegetable broth",
            "Vegetable mix, canned",
            "Vermouth",
            "Vinegar",
            "Vodka",
            "Wakame",
            "Walnut oil",
            "Walnuts",
            "Water",
            "Watermelon",
            "Watermelon seed",
            "Wheat brans",
            "Wheat flakes",
            "Wheat flour",
            "Wheat germ",
            "Wheat germ oil",
            "Wheat gluten",
            "Wheat sprouts",
            "Wheatgrass",
            "Whey",
            "Whey powder",
            "Whipping cream",
            "Whiskey",
            "White bread / Wheat bread",
            "White malt",
            "White mold cheese",
            "White radish",
            "Whitefish roe",
            "Whiting",
            "Whole grain breakfast cereals",
            "Whole grain rice",
            "Whole grain semolina",
            "Whole wheat flour",
            "Wholemeal pasta",
            "Wild boar meat",
            "Wild rice",
            "Wild strawberries",
            "Wine",
            "Wine vinegar",
            "Wine, alcohol-free",
            "Worcester sauce",
            "Xanthan gum (E 415)",
            "Xylitol (E967)",
            "Yam",
            "Yeast",
            "Yeast extract",
            "Yeast pastry dough, frozen",
            "Yoghurt",
            "Zefir"

        ];

        foreach ($productIngredients as $ingredient) {
            ProductIngredient::create([
                'name' => $ingredient,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
