<?php

return [
    'ingredients' => 'Ingredients',
    'allergens' => 'Allergens',
    'consumingGuide' => 'Consuming Guide',
    'storingConditions' => 'Storing Conditions',
    'newProduct' => 'New Product',
    'delete' => 'Delete',
    'save' => 'Save',
    'general' => 'General',
    'preparationInfo' => 'Preparation info',
    'consumerInfo' => 'Consumer info',
    'thisInformationCanBeUsedOnTheProductLabelIngredientsAndAllergensAreAutogeneratedAccordingToYourRecipeButYouAreAbleToChangeItAccordingToNeed' => 'This information can be used on the product label. Ingredients and allergens are autogenerated according to your recipe but you are able to change it according to need.',
];
